name: Build Kerberos LaTeX document
on:
  - pull_request

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v6
      - name: Compile Kerberos LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: paper-autotools-python.tex
          args: '-pdf -file-line-error -interaction=nonstopmode -shell-escape'
          working_directory: paper
